### ISSUE TITLE
Please add support for new model lv600s_humidifier

### ISSUE THREAD

**Issue by sergezab** [pschroeder89/homebridge-levoit-humidifiers#13]
**Is your feature request related to a problem? Please describe:**

I've bought the newer model, and it's not supported by plugin due to the device type  "deviceType":"LUH-A602S-WUS"
**Describe the solution you'd like:**

Please add "deviceType":"LUH-A602S-WUS" to the list of supported devices, it operates like Classic_300S, but also has warm mist mode.
**Describe alternatives you've considered:**

**Additional context:**

**Comment by pschroeder89** [comment]
Hey @sergezab, this will not be an easy change since I don't have this unit and it's much different than the others. Since this model doesn't only have cool mist, we will need to look at the requests being made to VeSync from the humidifier to understand how to change the temperature of the mist.

Are you familiar with using Charles Proxy to capture requests and responses?

**Comment by sergezab** [comment]
Hi Paul,

Thank you so much for trying to help there.

I’ve heard about Charles Proxy, but never used it. Being in Software Development myself, I think I’ll be able to do that.

Let me know what kind of data you need from Charles Proxy?

Best,
Sergii Zabigailo

**Comment by sergezab** [comment]
Hi Paul,

I’ve installed the Charles Proxy and intercepted the communication with API.

Please find the session recording attached.

Let me know if you need anything else.

Thank you!

Best,
Sergii Zabigailo

**Comment by pschroeder89** [comment]
Thanks for posting the detailed Charles requests @sergezab! I will take a look into this tomorrow. At first, I may just add support for cool mist and add the warm mist option later.

**Comment by pschroeder89** [comment]
1.4.0 is published with LV600S, cool mode only.

I have another question about the warm mode: Does it have its own levels? In the requests, I see that there are 3 levels of warmth. Does the Mist Level also need to be set, and the Warm mode heats that Mist Level? 

For instance, if I wanted the warmest and highest mist level, would I need to set Mist Level = 9 and Warm Level = 3?

Thanks in advance!

**Comment by sergezab** [comment]
Thank you so much on working on new model support. 
1. yes, there is 3 levels of warmth

2. yes, when you set the mist max level, humidifier stops both warms and/or cold mist as soon as the max humidity level is reached. Moreover cool mist and warm mist are 2 independent ways of mist generation. So, I can have cool on lev 9 or I can have warm on lev 3 or I can have both working for maximum humidity generation. 
3. Yes, I’m using mist lvl 9 and warm lvl 3  to make humidifier to output the maximum mist and reach the humidity level the fastest. We have a very dry air here in Utah, and that’s the only mode that works :)

**Comment by pschroeder89** [comment]
@sergezab I needed to refactor a whole bunch of things for 1.5.0-beta5. 
Once I feel it's been tested enough, I'll publish 1.5.0, and then add the new fan control for Warm Mist. If you take a look at the new beta, you'll see there is a Cool Mist fan. For the LV600s, I will be adding a Warm Mist fan as well, probably as 1.6.0.

Sorry for the delay on this ticket, but I wanted to get the other things addressed first.

**Comment by dfbills** [comment]
Thanks @pschroeder89 and @pschroeder89!  I also just got the 600s and have enjoyed using the software with my Classic 300S.

**Comment by pschroeder89** [comment]
Version 1.6.0-beta1 is pushed with support for Warm Mist Mode. It exposes a new fan control that has 0 (Off), 1, 2, and 3 levels.
Please test the feature and give feedback, since I can't test this myself. Also, please [consider sponsoring](https://github.com/sponsors/pschroeder89) so I can better test new features across models! Thank you!

**Comment by pschroeder89** [comment]
Let's open testing discussion, issues found, etc. to here: https://github.com/pschroeder89/homebridge-levoit-humidifiers/discussions/17

@dfbills @sergezab if you get some time to test, it would be much appreciated

**Comment by sergezab** [comment]
Thank you so much, @pschroeder89, for adding new functionality and supporting the latest devices! Your work is crucial for the air control in my home!

**Comment by dfbills** [comment]
@pschroeder89 After updating to v1.6.0-beta3, I can now see the controls exposed in HomeKit, but most of the values displayed are wrong/reserved and very few of the controls are actually working.

**Comment by sergezab** [comment]
@dfbills, please check my comment in #17
