### ISSUE TITLE
Setting auto mode turns device off

### ISSUE THREAD

**Issue by michaeldonovan** [pschroeder89/homebridge-levoit-humidifiers#2]
First off, thanks for putting this together, this is super useful.

I tried it with my Classic 300S and everything seems to be working great except auto mode. When I set the device to auto via HomeKit the device turns off. It's not just that the mist turns off, the device shows up as off in the VeSync app. This happens regardless of what the target humidity is set to. Also, if I set the device to auto mode in the VeSync app, it shows up as being in manual mode in homekit.

Let me know if there's any other information I can provide that'd be helpful. I might try to dig into the code a bit if I have some time this weekend.

Thanks!

**Comment by pschroeder89** [comment]
Thanks for the bug! I have also been seeing this but haven't had a lot of time to dig into it. 
I should be able to take a look this weekend.

**Comment by kurktchiev** [comment]
Can confirm it’s doing the same thing for me as well on the 300s

**Comment by kreeger** [comment]
So far as I can tell and based on my limited familiarity with the Vesync API (I sniffed out the request from their app using Charles on my phone), the API call to the Vesync API looks good and right, and `mode` should be set to `"auto"` (and it is!) — gonna check and see if debug mode gives me anything interesting.

**Comment by pschroeder89** [comment]
Thanks @kreeger. Still haven't taken a look, but that's very helpful. From your logs, it seems like switching to Auto is not calling changeMode, but setSwitch. I'll try to get to this in an hour or so

**Comment by pschroeder89** [comment]
I've published this fix in `homebridge-levoit-humidifiers@1.2.6`

Here's the PR: https://github.com/pschroeder89/homebridge-levoit-humidifiers/pull/4

The auto mode still can't be adjusted currently FWIW.

**Comment by michaeldonovan** [comment]
Works great, thanks!

**Comment by kurktchiev** [comment]
seems to be working on my end as well. or at least it doesnt just shut itself off.
