### ISSUE TITLE
[Device Request]

### ISSUE THREAD

**Issue by jarvismeier** [pschroeder89/homebridge-levoit-humidifiers#36]
**Model number:** Oasis Smart Humidifer. (configModule":"WFON_AHM_LUH-A451S-WUS_US")

**Number of cool mist levels:**
9
**Number of warm mist levels:**
3
**Auto mode?**
Yes
**Sleep mode?**
Yes
**Night Light?**
No
**Any other features not listed above?**
No

**Comment by pschroeder89** [comment]
Hey @jarvismeier, I will get this added later this week. Thanks for writing it up!

**Comment by pschroeder89** [comment]
@jarvismeier I have published version 1.7.6-beta1. Would you mind testing it when you can? 

In your ticket, I see `LUH-A451S-WUS`, but the actual model number appears to be `LUH-O451S-WUS` according to the manual. If 1.7.6-beta1 doesn't work, let me know and I will try with `LUH-A451S-WUS` instead.

Thanks in advance!

**Comment by jarvismeier** [comment]
This beta works!  Thanks

**Comment by haxo93** [comment]
I’m having trouble. I’m on the beta version, but I still only see my LUH-A602S-WUS and not my new LUH-O451S-WUS. Any suggestions? I tried a full uninstall and reinstall already.

**Comment by haxo93** [comment]
> I’m having trouble. I’m on the beta version, but I still only see my LUH-A602S-WUS and not my new LUH-O451S-WUS. Any suggestions? I tried a full uninstall and reinstall already.

I seem to have got it working by enabling a child bridge and adding that

**Comment by pschroeder89** [comment]
Interesting @haxo93. If you'd be willing to try again without the child bridge, could you enable debug mode and paste any output or errors you see?
I'm not sure why that behavior would happen.
Thanks!
