### ISSUE TITLE
[Device Request]

### ISSUE THREAD

**Issue by kurteous** [pschroeder89/homebridge-levoit-humidifiers#41]
**Model number:** LUH-D301S-WUSR - This is a Dual 200S, purchased in the US. The `deviceType` returned in the devices query is that, and `deviceName` is "Levoit Smart Cool Ultrasonic Humidifier". I manually updated `deviceTypes.d.ts` and `deviceTypes.js` in a deployed instance and now it shows up in HomeKit.

**Comment by pschroeder89** [comment]
Ah, I just found some documentation that this model has a night light and supports sleep mode. 1.8.3 is published with both of those toggles available, now.

**Comment by kurteous** [comment]
Looking good! Thanks for the super quick update.
