### ISSUE TITLE
OasisMist 451S

### ISSUE THREAD

**Issue by nyjklein** [pschroeder89/homebridge-levoit-humidifiers#47]
**Model number: OasisMist 451S (LUH-O451S-WUS)**

**Number of cool mist levels: 9**

**Number of warm mist levels:3**

**Auto mode? Y**

**Sleep mode? Y**

**Night Light? N**

**Any other features not listed above?
Display Toggle
Humidity Sensor**

I'm not sure if this is any different than the 450S. But I don't think it's working right. If I'm in Auto mode, then turn on the Sleep toggle it goes into Sleep mode as expected. If I then toggle Sleep mode off, I would expect it to go back to Auto. But nothing happens. It stays in sleep mode. If I toggle the main humidifier off, it switches off. But when I toggle it again, it comes on but is still in sleep mode. Not sure how to get it out of sleep mode other than using the app or the physical auto switch.

**Comment by pschroeder89** [comment]
Thanks @nyjklein ...do you know if this worked previously? I recently made a small change for Oasis that I think might be the culprit

**Comment by nyjklein** [comment]
I don't know. I just got the device setup yesterday. 

Should I install the previous version and see if that works differently?

**Comment by nyjklein** [comment]
Closed accidentally.

**Comment by pschroeder89** [comment]
Yeah this was my bad. That log helped a lot. I'll have this fixed later today

**Comment by pschroeder89** [comment]
That last log looks like your humidifier unregistered from VeSync briefly due to an internet drop...we only throw that error if VeSync gives the status: `"device offline"`

I just published 1.8.6, which hopefully fixes the Sleep Mode switch. Could you give it a shot?

**Comment by pschroeder89** [comment]
Sweet! That humidifier shares a lot in common with the LV600s, so I assumed it handled Auto mode differently like the LV600s does. Turns out it doesn't! Thanks for validating the fix, will close this bug.
