### ISSUE TITLE
[Request] Toggle to Disable Humidity Sensor Reporting in Homekit

### ISSUE THREAD

**Issue by FarawaySounds** [pschroeder89/homebridge-levoit-humidifiers#54]
**Is your feature request related to a problem? Please describe:**

I'd like to be able to disable humidity reporting from the humidifier. I have a homepod that reports humidity for the room and now Siri when asked about the humidity replies with the range of humidities from both the HomePod and the humidifier instead of just a single value. 

**Describe the solution you'd like:**
In the Homebridge settings for the plugin I'd like to he able to toggle off the humidity sensor.

**Comment by pschroeder89** [comment]
Hey @FarawaySounds, I'll look into this next week. Pretty sure this is simple to implement

**Comment by pschroeder89** [comment]
@FarawaySounds Please try 1.9.2-beta1. There is a setting in the config to disable the sensors now. I haven't tested it myself, so please check it out.

**Comment by pschroeder89** [comment]
Published in 1.10.1

**Comment by FarawaySounds** [comment]
Works great! Thanks!
