### ISSUE TITLE
Adding additional humidifiers

### ISSUE THREAD

**Issue by hansw1204** [pschroeder89/homebridge-levoit-humidifiers#72]
**Is your feature request related to a problem? Please describe:**
I added a second Humidifier (LV600S) to my exisiting LV200S. It shows up in Homebridge and HomeKit but there is only one config  and it is for the original LV200S which is configured as a child bridge.

**Describe the solution you'd like:**
Being able to add a second child bridge for the second humidifier so I can configure it separately.

**Describe alternatives you've considered:**
Adding a new device to HomeKit with the Homebridge code but I fear that will generate a second instance since the device already shows up in HomeKit

**Additional context:**
None of the switches in the Levoit tiles show any labels which may be related to  the config  issue

**Comment by pschroeder89** [comment]
I don't think I'll be implementing multiple configs, but you're welcome to add it yourself. Tracking multiple configs per device would require a lot of refactor work that I don't currently have time for.
