### ISSUE TITLE
[Device Request] Vista 200 Air Purifier

### ISSUE THREAD

**Issue by sageDieu** [pschroeder89/homebridge-levoit-humidifiers#73]
Just got this lil guy from Best Buy on sale, hoping to add it to some HomeKit scenes. Happy to test and troubleshoot. Thanks in advance!

**Model number:**
Vista 200
https://levoit.com/collections/air-purifiers-for-small-spaces-up-to-200-sq-ft/products/vista200-true-hepa-air-purifier

**Number of mist levels:**
N/A (no mist feature)

**Number of warm mist levels:**
N/A (no mist feature)

**Auto mode?**
N/A (no humidifier feature)

**Sleep mode?**
Yes

**Night Light?**
Yes

**Any other features not listed above?**
Fan speed (sleep/low/med/high)

**Comment by sageDieu** [comment]
Here's a printout of debug mode in case it's helpful:

`[DEBUG]: [GET DEVICES] Device List -> JSON: [{"deviceRegion":"US","isOwner":true,"authKey":null,"deviceName":"Bedroom Purifier","deviceImg":"https://image.vesync.com/defaultImages/deviceDefaultImages/wfbo_apr_lap-c201s-ausr_us_240.png","cid":"vsaq60b782248b596385be2add01ffa0","deviceStatus":"on","connectionStatus":"online","connectionType":"wifi+BTOnboarding","deviceType":"LAP-C201S-AUSR","type":"wifi-air","uuid":"ba748a16-486c-469c-b1a9-10b5ba4102b6","configModule":"WFBO_APR_LAP-C201S-AUSR_US","macID":"0c:b8:15:37:24:e6","mode":null,"speed":null,"currentFirmVersion":null,"subDeviceNo":null,"subDeviceType":null,"deviceFirstSetupTime":"Jan 19, 2024 6:12:57 PM","subDeviceList":null,"extension":{"airQuality":-1,"airQualityLevel":1,"mode":"manual","fanSpeedLevel":"2"},"deviceProp":null}]`

**Comment by pschroeder89** [comment]
Hey @sageDieu you actually want to check out https://github.com/RaresAil/homebridge-levoit-air-purifier

**Comment by sageDieu** [comment]
Ah thanks for the redirect, came here since your plugin had the most recent update :) will give that one a try!
