### ISSUE TITLE
Unhandled Rejection in HOOBS

### ISSUE THREAD

**Issue by NeilJonesOnline** [pschroeder89/homebridge-levoit-humidifiers#77]
**Describe The Bug:**
Trying to configure HOOBS plugin running on child bridge for Levoit 300S Humidifier.
Get the error: WARNING unhandled rejection: TypeError: Cannot read properties of undefined (reading 'apiTimeout')
HOOBS bridge goes down

**To Reproduce:**
Create child bridge, install plugin, enter credentials in visual config

**Expected behavior:**
No error

**Logs:**
03/04/2024, 13:01:55HOOBS (Levoit Humidifer) starting
03/04/2024, 13:01:58HOOBS (Levoit Humidifer)Loaded plugin 'homebridge-levoit-humidifiers'
03/04/2024, 13:01:58HOOBS (Levoit Humidifer)Loading 1 platforms...
03/04/2024, 13:01:58HOOBS (Levoit Humidifer)Levoit Humidifiers[DEBUG]: [PLATFORM] Debug mode enabled
03/04/2024, 13:01:58HOOBS (Levoit Humidifer)WARNINGunhandled rejection: TypeError: Cannot read properties of undefined (reading 'apiTimeout')

**Plugin Config:**
{
    "platform": "LevoitHumidifiers",
    "name": "Levoit Humidifiers",
    "email": "neil@nxxxxxxy.com",
    "password": "xxxx",
    "enableDebugMode": true
}

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.12.4
* **Homebridge Version**:  1.70
* **Node.js Version**:  16.20.2
* **NPM Version**:  n/k
* **Operating System**:  HOOBS 4.3.1

**Comment by pschroeder89** [comment]
Hey @NeilJonesOnline, I won't be able to fix this until next week but in the meantime, you can add this to your config:

```
options: {
  apiTimeout: 15000
}
```

I think the reason this happens is that you're using node 16, but I'll fix it in a future release

**Comment by NeilJonesOnline** [comment]
Great, will give that a try thanks Paul. Neil On 5 Apr 2024, at 11:30, Paul Schroeder ***@***.***> wrote:﻿
Hey @NeilJonesOnline, I won't be able to fix this until next week but in the meantime, you can add this to your config:
options: {
  apiTimeout: 15000
}

I think the reason this happens is that you're using node 16, but I'll fix it in a future release

**Comment by pschroeder89** [comment]
This should be fixed in 1.14.1
