### ISSUE TITLE
Question: Is its possible to add a second humidifier

### ISSUE THREAD

**Issue by hansw1204** [pschroeder89/homebridge-levoit-humidifiers#81]
**Is your feature request related to a problem? Please describe:**
I bought a second Levoit LV600S but it doesn't show up in HomeKit

**Describe the solution you'd like:**
I would like the second Humidifier to show up in HomeKit 

**Describe alternatives you've considered:**
None

**Additional context:**

**Comment by pschroeder89** [comment]
I currently have 4 humidifiers, so it should work. Can you provide debug logs from the moment the plugin starts?

**Comment by hansw1204** [comment]
Thank you! It's all good now, both my humidifiers show up, and everything works perfectly.
